"""Declared orchestration entry: re-exports flow types, ingest, protocol, holds, and attendance.

API may import this module only. Implementation lives in the flows_* siblings.
"""

from history import record_event_state
from orchestrator.attendance_schedule import (  # re-exported: api may only import orchestrator.flows
    AttendanceDispatch,
    attendance_dispatch,
)
from orchestrator.capabilities import CapabilityDescriptor, build_role_aware_system_context, visible_capabilities
from orchestrator.event_queue import PolicyAwareEventQueue, SerialEventQueue, WorkItem
from orchestrator.flows_direct_lane import (
    DirectLaneAction,
    DirectLaneResult,
    attempt_direct_lane,
    classify_direct_lane,
    run_direct_lane,
)
from orchestrator.flows_execution import (
    DroneSelectionReplyResult,
    EventDataReplyResult,
    FlowDeps,
    FlowOutcome,
    FlowResult,
    _VERDICT_TO_OUTCOME,
    _deadline_failure,
    _log_event_outcome,
    _log_reply_latency,
    _now,
    _record_outcome_with_report,
    assemble_core_agents,
    execute_steps,
)
from orchestrator.flows_hold_sweep import (
    HoldSweepScheduler,
    apply_drone_selection_reply,
    apply_event_data_reply,
    continue_after_clarification,
    resolve_approval,
    resolve_clarification,
    resume_after_approval,
    resume_after_clarification,
    sweep_unresolved_holds,
)
from orchestrator.flows_ingest import (
    begin_report,
    begin_request,
    process_message,
    process_report,
    process_request,
    run_report_extraction,
    _model_invoker_for,
)
from orchestrator.flows_protocol import (
    _apply_required_fields_gate,
    _continue_after_required_fields,
    _execute_protocol_plan,
    _finish_protocol_assessment,
    _finish_with_resource_unavailable,
    _look_up_precedent_if_possible,
    _persist_step_outcomes,
    _persist_step_plan,
    _prior_outcomes,
    _run_protocol,
    _step_from_row,
    continue_after_approval,
    continue_from_risk_assessment,
    decline,
    resume_after_event_data,
)
from orchestrator.group_routing import (  # re-exported: api may only import orchestrator.flows
    GROUP_CHAT_TYPES,
    MAIN_AGENT_TARGET,
    GroupBinding,
    GroupNotRegisteredError,
    GroupRoutingTable,
    InvalidRoutingTargetError,
    is_scoped_target,
    resolve_scope,
    scope_deps,
)
from orchestrator.holds import protocol_requires_approval
from orchestrator.reasoning import (
    OrchestrationParseError,
    answer_conversationally,
    answer_question,
    answer_question_from_plan,
    classify_intent,
    plan_message,
)
from orchestrator.report_composer import ReportComposerAgent, compose_report  # re-exported: api may only import orchestrator.flows
from orchestrator.situational_picture import (  # re-exported: api may only import orchestrator.flows
    SituationalPicture,
    build_situational_picture,
    compose_picture_from_step_outcomes,
    picture_protocol,
    question_requests_picture,
    read_picture_directly,
)

__all__ = [
    "AttendanceDispatch",
    "CapabilityDescriptor",
    "DirectLaneAction",
    "DirectLaneResult",
    "DroneSelectionReplyResult",
    "EventDataReplyResult",
    "FlowDeps",
    "FlowOutcome",
    "FlowResult",
    "GROUP_CHAT_TYPES",
    "GroupBinding",
    "GroupNotRegisteredError",
    "GroupRoutingTable",
    "HoldSweepScheduler",
    "InvalidRoutingTargetError",
    "MAIN_AGENT_TARGET",
    "OrchestrationParseError",
    "PolicyAwareEventQueue",
    "ReportComposerAgent",
    "SerialEventQueue",
    "SituationalPicture",
    "WorkItem",
    "answer_conversationally",
    "answer_question",
    "answer_question_from_plan",
    "apply_drone_selection_reply",
    "apply_event_data_reply",
    "assemble_core_agents",
    "attendance_dispatch",
    "attempt_direct_lane",
    "begin_report",
    "begin_request",
    "build_role_aware_system_context",
    "build_situational_picture",
    "classify_direct_lane",
    "classify_intent",
    "compose_picture_from_step_outcomes",
    "compose_report",
    "continue_after_approval",
    "continue_after_clarification",
    "continue_from_risk_assessment",
    "decline",
    "execute_steps",
    "is_scoped_target",
    "plan_message",
    "process_message",
    "process_report",
    "process_request",
    "protocol_requires_approval",
    "record_event_state",
    "resolve_approval",
    "resolve_clarification",
    "resolve_scope",
    "resume_after_approval",
    "resume_after_clarification",
    "resume_after_event_data",
    "run_direct_lane",
    "run_report_extraction",
    "scope_deps",
    "sweep_unresolved_holds",
    "visible_capabilities",
]
